image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r assets data index.html main.js styles.css site.webmanifest robots.txt sitemap.xml _headers _redirects public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
